<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:element name="releve">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="dateReleve" type="xsd:date"/>
				<xsd:element name="solde" type="xsd:integer"/>
				<xsd:element name="operations" type="operations_type"/>
			</xsd:sequence>
			<xsd:attribute name="RIB" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="operations_type">
		<xsd:sequence>
			<xsd:element name="operation" minOccurs="1" maxOccurs="unbounded" type="operation_type"/>
		</xsd:sequence>
		<xsd:attribute name="dateDebut" type="xsd:date" use="required"/>
		<xsd:attribute name="dateFin" type="xsd:date" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="operation_type">
		<xsd:attribute name="type" type="xsd:string" use="required"/>
		<xsd:attribute name="date" type="xsd:date" use="required"/>
		<xsd:attribute name="montant" type="xsd:integer" use="required"/>
		<xsd:attribute name="description" type="xsd:string" use="required"/>
	</xsd:complexType>

</xsd:schema>
